---
# tasks file for server
- name: Add apt key
  apt_key: id='EA312927' keyserver='hkp://keyserver.ubuntu.com:80' state='present'
  
- name: Add Mongodb Repo
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse' state='present' update_cache='yes'

- name: Install required software
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - mongodb-server

- name: PhpMoadmin Install
  copy: src=moadmin.php dest=/var/www/html/ owner=www-data group=www-data mode=0664
  