---
# tasks file for php
- name: Install nodejsnpm
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - nodejs
    - npm
    - nodejs-legacy

- name: Install npm packages
  npm: name={{ item }} global=yes state=present
  with_items:
    - forever