---
# tasks file for php
- name: Install php extensions
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - php5.6-cli
    - php-zip
    - libapache2-mod-php
    - php-cgi
    - php-cli  
    - php-fpm 
    - php-dev  
    - php-curl  
    - php-gd   
    - php-mbstring 
    - php-mcrypt 
    - php-mysql 
    - php-pgsql  
    - libapache2-mod-php5.6 
    - php5.6-cgi 
    - php5.6-cli 
    - php5.6-phpdbg 
    - php5.6-fpm 
    - libphp5.6-embed 
    - php5.6-dev 
    - php5.6-common 
    - php5.6-curl 
    - php5.6-gd 
    - php5.6-imap 
    - php5.6-intl 
    - php5.6-ldap 
    - php5.6-mysql 
    - php5.6-pgsql 
    - php5.6-pspell 
    - php5.6-recode 
    - php5.6-snmp 
    - php5.6-sqlite3 
    - php5.6-sybase 
    - php5.6-tidy 
    - php5.6-opcache 
    - php-xdebug 
    - php5.6-json 
    - php-memcached  
    - php5.6-bz2 
    - php5.6-mcrypt 
    - php5.6-odbc 
    - php5.6-readline 
    - php-bz2 
    - php-odbc 
    - php5.6-interbase 
    - php5.6-xmlrpc 
    - php5.6-enchant 
    - php5.6-gmp 
    - php5.6-xsl 
    - php-memcache 
    - php5.6-mbstring 
    - php5.6-soap 
    - php5.6-xml 
    - php5.6-zip 
    - php-xml   
    - php-pecl-http 
    - php-stomp 
    - php-mongo 
    - php5.6-dba 

- name: restart apache
  service: name=apache2 state=restarted
  sudo: yes 